#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Maison Dorée — Soroban Contract Deployment Script
# Deploys the negative_sampler contract to Stellar Testnet
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONTRACT_DIR="${SCRIPT_DIR}/contracts/negative_sampler"
ENV_FILE="${SCRIPT_DIR}/.env"
NETWORK="testnet"
WASM_FILE="${CONTRACT_DIR}/target/wasm32-unknown-unknown/release/negative_sampler.wasm"

echo "🍽  Maison Dorée — Contract Deployment"
echo "======================================="

# Step 1: Check prerequisites
echo ""
echo "📋 Checking prerequisites..."

if ! command -v stellar &> /dev/null && ! command -v soroban &> /dev/null; then
    echo "❌ Stellar CLI not found. Install with:"
    echo "   cargo install --locked stellar-cli --features opt"
    exit 1
fi

CLI_CMD="stellar"
if ! command -v stellar &> /dev/null; then
    CLI_CMD="soroban"
fi

echo "✅ Using CLI: ${CLI_CMD}"

# Step 2: Build the contract
echo ""
echo "🔨 Building contract..."
cd "${CONTRACT_DIR}"
cargo build --target wasm32-unknown-unknown --release

if [ ! -f "${WASM_FILE}" ]; then
    echo "❌ WASM file not found at ${WASM_FILE}"
    exit 1
fi

echo "✅ Contract built: $(du -h "${WASM_FILE}" | cut -f1)"

# Step 3: Configure network
echo ""
echo "🌐 Configuring testnet..."
${CLI_CMD} network add \
    --global testnet \
    --rpc-url https://soroban-testnet.stellar.org:443 \
    --network-passphrase "Test SDF Network ; September 2015" \
    2>/dev/null || true

# Step 4: Check/create identity
IDENTITY_NAME="deployer"
if ! ${CLI_CMD} keys address "${IDENTITY_NAME}" 2>/dev/null; then
    echo "🔑 Generating deployer identity..."
    ${CLI_CMD} keys generate "${IDENTITY_NAME}" --network testnet
    echo "💰 Funding account from friendbot..."
    ${CLI_CMD} keys fund "${IDENTITY_NAME}" --network testnet
else
    echo "✅ Using existing deployer identity"
fi

DEPLOYER_ADDRESS=$(${CLI_CMD} keys address "${IDENTITY_NAME}")
echo "   Address: ${DEPLOYER_ADDRESS}"

# Step 5: Deploy contract
echo ""
echo "🚀 Deploying contract to testnet..."
CONTRACT_ID=$(${CLI_CMD} contract deploy \
    --wasm "${WASM_FILE}" \
    --source "${IDENTITY_NAME}" \
    --network testnet)

echo "✅ Contract deployed!"
echo "   Contract ID: ${CONTRACT_ID}"

# Step 6: Initialize contract
echo ""
echo "⚙️  Initializing contract (k=10)..."
${CLI_CMD} contract invoke \
    --id "${CONTRACT_ID}" \
    --source "${IDENTITY_NAME}" \
    --network testnet \
    -- \
    initialize \
    --admin "${DEPLOYER_ADDRESS}" \
    --max_size 10

echo "✅ Contract initialized"

# Step 7: Verify
echo ""
echo "🔍 Verifying deployment..."
STATS=$(${CLI_CMD} contract invoke \
    --id "${CONTRACT_ID}" \
    --source "${IDENTITY_NAME}" \
    --network testnet \
    -- \
    get_stats)

echo "   Stats: ${STATS}"

# Step 8: Save to .env
echo ""
echo "💾 Saving configuration..."
cat > "${ENV_FILE}" << EOF
# Maison Dorée — Environment Configuration
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Soroban Contract
CONTRACT_ID=${CONTRACT_ID}
NETWORK=testnet
RPC_URL=https://soroban-testnet.stellar.org:443
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

# MongoDB
MONGODB_URI=mongodb+srv://mustafaterr_db_user:ipBu9XmPvbJsarqD@cluster3.pyp4ts1.mongodb.net/cluster3
DB_NAME=cluster3

# Deployer
DEPLOYER_ADDRESS=${DEPLOYER_ADDRESS}
EOF

echo "✅ Configuration saved to .env"
echo ""
echo "======================================="
echo "🎉 Deployment complete!"
echo ""
echo "Contract ID: ${CONTRACT_ID}"
echo "Network:     testnet"
echo "Explorer:    https://stellar.expert/explorer/testnet/contract/${CONTRACT_ID}"
echo ""
echo "Next steps:"
echo "  1. Update your frontend with the contract ID"
echo "  2. Start the Leptos app: cargo leptos watch"
echo "  3. Open http://localhost:3000"
echo "======================================="
